### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by Ogerets** [EdricChan03/action-build-deploy-ghpages#29]
Happens on v2.6.0 for mac os build

**Comment by EdricChan03** [comment]
Unfortunately, Docker container actions appear to be not supported on environments apart from Linux. Please see [this existing GitHub Community discussion](https://github.com/orgs/community/discussions/25777#discussioncomment-3249229) for more info.

Let me know if you have additional queries.

**Comment by Ogerets** [comment]
Got it, thanks. 
Maybe include this info to Readme to save fellows like me?
